import React, { useState, useEffect } from 'react';
import axios from 'axios';
import '../App.css';

const Roadmap = ({ user }) => {
  const [loading, setLoading] = useState(true);
  const [roadmapContent, setRoadmapContent] = useState('');
  const [generating, setGenerating] = useState(false);

  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { fetchDashboard(); }, []);

  const fetchDashboard = async () => {
    try {
      const token = localStorage.getItem('token');
      const res = await axios.get('http://localhost:5000/api/user/dashboard', {
        headers: { Authorization: `Bearer ${token}` }
      });
      // Auto generate roadmap if enough data
      if (res.data.test_history && res.data.test_history.length > 0) {
        generateRoadmap(res.data.test_history);
      } else {
        setGenerating(false);
        setRoadmapContent('**Welcome to CodeMentorAI!**\n\nTake your first Adaptive Test in any subject. Once we have a baseline of your strengths and weaknesses, our AI mentor will generate a personalized 4-week study plan just for you.');
        setLoading(false);
      }
    } catch (err) {
      console.error(err);
      setLoading(false);
    }
  };

  const generateRoadmap = async (history) => {
    setGenerating(true);
    setLoading(false);
    try {
      // Find weakest areas roughly based on missing accuracy
      const weak_areas = [...new Set(history.filter(t => t.accuracy < 70).map(t => t.subject))].slice(0, 3);
      
      const token = localStorage.getItem('token');
      const res = await axios.post('http://localhost:5000/api/ai/roadmap', {
        weak_areas: weak_areas,
        level: user?.capability_level || 'Intermediate'
      }, { headers: { Authorization: `Bearer ${token}` } });
      
      setRoadmapContent(res.data.roadmap);
    } catch (err) {
      console.error(err);
      setRoadmapContent('<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{verticalAlign:"middle", marginRight:8, color:"#F59E0B"}}><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12.01" y2="17"></line></svg> Warning: Something went wrong generating your roadmap. Please check your AI connection.');
    } finally {
      setGenerating(false);
    }
  };

  // Convert simple markdown to HTML (naive parser for headers and bolding and lists)
  const parseMarkdown = (md) => {
    let html = md.replace(/\n\n/g, '</p><p>');
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/## (.*?)</g, '<h2 style="font-size:18px; margin-top:24px; color:var(--text);">$1</h2><');
    html = html.replace(/- (.*?)</g, '<li style="margin-bottom:8px; line-height:1.5;">$1</li><');
    html = html.replace(/<p><li/g, '<ul style="padding-left:20px;"><li');
    html = html.replace(/<\/li><\/p>/g, '</li></ul>');
    return `<p>${html}</p>`;
  };

  if (loading) return <div className="app-layout"><div className="loading">Analyzing your learning profile...</div></div>;

  return (
    <div className="app-layout" style={{ paddingTop: '64px' }}>
      <div style={{ background: 'var(--grad-soft)', padding: '48px 0 36px', borderBottom: '1px solid var(--border)' }}>
        <div className="container" style={{ maxWidth: '900px' }}>
          <h1 style={{ fontSize: '32px', fontWeight: 900, marginBottom: '8px', color: 'var(--orange-600)', display: 'flex', alignItems: 'center', gap: '12px' }}>
            
            AI Learning Roadmap
          </h1>
          <p style={{ fontSize: '16px', color: 'var(--text-2)', margin: 0 }}>
            Your curated 4-week study plan generated by analyzing your adaptive test performance.
          </p>
        </div>
      </div>

      <div className="container" style={{ maxWidth: '900px', padding: '40px 20px' }}>
        <div className="card" style={{ minHeight: '500px', position: 'relative' }}>
          {generating ? (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '400px' }}>
              
              <h2 style={{ marginTop: '20px', color: 'var(--orange-600)' }}>Building your customized roadmap...</h2>
              <p style={{ color: 'var(--text-muted)' }}>We are cross-referencing your weak areas with NPTEL curriculums.</p>
            </div>
          ) : (
            <div 
              style={{ fontSize: '15px', lineHeight: '1.7', color: 'var(--text-2)' }}
              dangerouslySetInnerHTML={{ __html: parseMarkdown(roadmapContent) }} 
            />
          )}
        </div>
      </div>
    </div>
  );
};

export default Roadmap;
